import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PDFReportOptions {
  metrics?: Array<{
    id: string;
    name: string;
    generation: number;
    consumption: number;
    balance: number;
    holderLevel: number;
    status: string;
  }>;
  nodes?: Array<any>;
  auditLogs?: Array<any>;
  reportTitle: string;
  dateRange: string;
  operatorName: string;
}

export function generateGasMindPDFReport(options: PDFReportOptions): void {
  const doc = new jsPDF();
  const { metrics = [], reportTitle, dateRange, operatorName } = options;

  // Header background
  doc.setFillColor(15, 15, 18);
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('GASMIND - Tata Steel Energy Intelligence', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 200, 200);
  doc.text(`${reportTitle} | ${dateRange}`, 14, 28);
  doc.text(`Generated by: ${operatorName}`, 14, 34);

  // Divider
  doc.setDrawColor(60, 60, 65);
  doc.setLineWidth(0.5);
  doc.line(14, 45, 196, 45);

  // Section Heading
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 20, 20);
  doc.text('By-Product Gas Stream Summary', 14, 55);

  // Table
  const tableData = metrics.map((m) => [
    m.id,
    m.name,
    `${m.generation.toLocaleString()} Nm³/h`,
    `${m.consumption.toLocaleString()} Nm³/h`,
    `${m.balance >= 0 ? '+' : ''}${m.balance.toLocaleString()} Nm³/h`,
    `${m.holderLevel}%`,
    m.status.toUpperCase()
  ]);

  autoTable(doc, {
    startY: 60,
    head: [['ID', 'Gas Stream', 'Generation', 'Consumption', 'Net Balance', 'Holder Lvl', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [24, 24, 27],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [245, 245, 248]
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    }
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      `GASMIND v1.0.0 Confidential - Fuel Management Dept, Tata Steel | Page ${i} of ${pageCount}`,
      14,
      288
    );
  }

  const cleanFileName = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  doc.save(`GASMIND_${cleanFileName}_Report.pdf`);
}
